// The bot's response logic
function getBotResponse(userMessage) {
    // A simple response logic
    const responses = {
        //Possible gretting data set 
        "hello": "Hi there! <BR><p class='p-001'>Use <code>/help</code> for finding mentors/course.</p>",
        "how are you?": "I'm doing well, thanks for asking! How about you?",
        "where are you from?": "I don't have a physical location since I'm a digital entity created by a Zenbot. My home is in the digital files, so to speak. Where are you from?",
        "what is your name?": "I'm your Zenbot!","hii": "I'm fine! Ready to help you out as usual,<br>Try <code>/help</code>","what is my name?": "How would I know? You tell me!","what is your full name?":"I'm known as a Zenbot, I don't have a full name in the traditional sense, but you can call me a Zenbot.",
        /* //ZenBot Related Dataset*/"what is Zenbot?":" A Zenbot is a computer program that simulates human conversation through voice commands or text chats or both. Zenbot, is an artificial intelligence (AI) feature that can be embedded and used through any major messaging application.","is how a chatbot works?":"Chatbots work using a combination of artificial intelligence (AI), natural language processing (NLP), and pre-programmed rules. Here's a basic overview of how they function Input Understanding: When you type a message, the chatbot uses NLP techniques to interpret your text. This involves breaking down your message into understandable components and identifying the key elements and intent. Processing: The chatbot then processes this input using algorithms and models to determine the appropriate response. It may use predefined rules, patterns, or machine learning models to generate an answer.Response Generation: Based on the processing, the chatbot generates a response. This could be a direct answer, a follow-up question, or a task execution (like booking an appointment or retrieving information).Learning and Improvement: More advanced chatbots use machine learning to improve over time. They analyze interactions, learn from user feedback, and refine their responses to provide better and more accurate answers in the future.Chatbots range from simple rule-based systems to sophisticated AI-driven models, depending on their design and intended use.",//hackathonrelatedDatasets
        "what is hackathon?":"A hackathon is an event, often lasting between 24 to 48 hours, where participants collaborate intensively on software or hardware projects. The goal is to develop a functioning prototype or solution by the end of the event. Hackathons can be focused on specific themes or challenges and typically involve coding, designing, and problem-solving. They are popular in tech communities and can foster innovation, teamwork, and skill development.",
        "define hackathon?":"A hackathon is an event, often lasting between 24 to 48 hours, where participants collaborate intensively on software or hardware projects. The goal is to develop a functioning prototype or solution by the end of the event. Hackathons can be focused on specific themes or challenges and typically involve coding, designing, and problem-solving. They are popular in tech communities and can foster innovation, teamwork, and skill development.",//hackathonrelatedDatasets
        "explain hackathon?":"A hackathon is an event, often lasting between 24 to 48 hours, where participants collaborate intensively on software or hardware projects. The goal is to develop a functioning prototype or solution by the end of the event. Hackathons can be focused on specific themes or challenges and typically involve coding, designing, and problem-solving. They are popular in tech communities and can foster innovation, teamwork, and skill development.",//AlphabetsrelatedDataSet
        "a":"A for Apple.","b":"What do you mean, Please elaborate more I could not understand?","c":"What do you mean,<br> Please elaborate more I could not understand?","d":"What do you mean,<br>Please elaborate more I could not understand?","e":"What do you mean, <br>Please elaborate more I could not understand?","f":"What do you mean,<br> Please elaborate more I could not understand?","g":"What do you mean,<br> Please elaborate more I could not understand?","h":"What do you mean,<br> Please elaborate more I could not understand?","i":"What do you mean,<br> Please elaborate more I could not understand?","j":"What do you mean,<br>Please elaborate more I could not understand?","k":"What do you mean, <br>Please elaborate more I could not understand?","l":"What do you mean, <br>Please elaborate more I could not understand?","m":"What do you mean, <br>Please elaborate more I could not understand?","n":"What do you mean, <br>Please elaborate more I could not understand?","o":"What do you mean, <br>Please elaborate more I could not understand?","p":"What do you mean, <br>Please elaborate more I could not understand?","q":"What do you mean, <br>Please elaborate more I could not understand?","r":"What do you mean, <br>Please elaborate more I could not understand?","s":"What do you mean, <br>Please elaborate more I could not understand?","t":"What do you mean, <br>Please elaborate more I could not understand?","u":"What do you mean, <br>Please elaborate more I could not understand?","v":"What do you mean, <br>Please elaborate more I could not understand?","w":"What do you mean, <br>Please elaborate more I could not understand?","x":"What do you mean, <br>Please elaborate more I could not understand?","y":"What do you mean, <br>Please elaborate more I could not understand?","z":"What do you mean, <br>Please elaborate more I could not understand?",//Alphabetdataset end
        "what are you doing?":"I'm just hanging out, <br>ready to help you need!.Type <code>/help</code> <br>I'm still learning and improving, <br>so I might make some mistakes or might being not able to find your deserving answers.",
        //CollegeDataSets                  COMMAND LIST COMMAND LIST COMMAND LIST COMMAND LIST
        "/help":"Provides help for chat controls.<br>Commands must always start with the '<code>/</code>' symbol and contain up to 32 characters,Type the command OR do copy and paste in Input field.<br> Use only lowercase text after the '<code>/</code>'.<br>Some commands list are given below:<br><br><table><tr><th>Command List</th><th>Functioning</th></tr>   <tr><td><code>/mentors</code></td><td>Names of Existing Mentors.</td></tr><tr><td><code>/datascience</code></td><td>All about Data Science</td></tr>   <tr><td><code>/cloudcomputing</code></td><td>Subject Cloud computing details</td></tr>   <tr><td><code>/ai</code></td><td>Artificial Intelligence details.</td></tr>   <tr><td><code>/cybersecurity</code></td><td>Subject CyberSecurity details..</td></tr>   </table>",
                        //Mentors name list
                // Example for next mentor: <tr><td><code>/mentorrbsingh</code></td><td>Career Advisior/specialist </td></tr>
        "/mentors":          "According to my dataset, these are some existing mentors till now.<br><br> <table><tr><th>Mentors List</th><th>Specialization</th></tr>   <tr><td><code>/mentorrbsingh</code></td><td>Career Advisior/specialist.</td></tr>   <tr><td><code>/mentorpragyachaudhary</code></td><td>Subject Expert [C/C++, Cloud Computing].</td></tr>   <tr><td><code>/mentorfalak</code></td><td>Professor of Data Science.</td></tr>   <tr><td><code>/mentordiwakaryadav</code></td><td>Subject Expert [Political Science].</td></tr>   </table>",
    
        //  /mentorRBsingh details dataset
        "/mentorrbsingh":"<b>R.B Singh<br><br>Director, SDGI University | Career Development Mentor & Advisor</b><br><br>With over 20 years of experience in the field of education, R.B. Singh is a distinguished professional, known for his expertise in both academic leadership and career development.<br> As the Director of SDGI University, he has been instrumental in shaping the institution’s success for several years.<br> His passion for guiding students and professionals has made him a trusted mentor in career development and advisory services.<br><br>    <p class='p-001'>Enter <code>/inforbsingh</code> for contact details to connect with your mentor.</p>",
        //  /inforbsingh contact details
        "/inforbsingh":"<b>Contact information [R.B Singh]:</b> <BR><BR> <p class='p-whatsapp-logo'><b>Whatsapp : </b><a class='p-whatsapp-link' href='https://web.whatsapp.com/' target='_blank'><abbr title='web.whatsapp'>+91 94581 70799</abbr></a></p> <BR> <p class='p-email-logo'><b>Email :</b> <a class='p-gmail-link' href='https://mail.google.com/mail/u/0/#inbox?compose=DmwnWstqwxJfbRDdbsFxpjBjWWtDxPpPWNlkpGLXVxGNxRVbtbXMfxfvmLBmVljfKmKwmFxDFsSg' target='_blank'><abbr title='Click to send Email'>rambhawansingh@gmail.com</abbr></a></p> <BR> <p class='p-phone-logo'><b>Phone :</b><span class='p-phone-link'><abbr title='select and copy'>+91 94581 70789</abbr></span></p>  <BR>   <p class='p-linkedin-logo'><b>LinkedIn :</b> <a class='p-linkedin-link' href='https://www.linkedin.com/feed/' target='_blank'><abbr title='Go to LinkedIn'><i>Not Available</i><abbr></a></p>",

        //   /mentorpragyachaudhary details dataset
        "/mentorpragyachaudhary":"<b>Prayga Chaudhary<br><br>Subject Expert, C/C++ and Cloud Computing | SDGI University</b><BR><BR>With 3 years of experience in the educational field, Prayga Chaudhary is a dedicated and dynamic teacher at SDGI University. She specializes in C/C++ programming and Cloud Computing, offering deep insights and practical knowledge to her students.<BR> Her expertise extends to guiding students towards successful careers in programming and cloud computing roles.  <BR><BR>  <p class='p-001'>Enter <code>/infopragyachaudhary</code> for contact details to connect with your mentor.</p>",
        //  /infopragyachaudhary contact details
        "/infopragyachaudhary":"<b>Contact information [Pragya Chaudhary]:</b> <BR><BR> <p class='p-whatsapp-logo'><b>Whatsapp : </b><a class='p-whatsapp-link' href='https://web.whatsapp.com/' target='_blank'><abbr title='web.whatsapp'>+91 +91 81262 90604</abbr></a></p> <BR> <p class='p-email-logo'><b>Email :</b> <a class='p-gmail-link' href='https://mail.google.com/mail/u/0/#inbox' target='_blank'><abbr title='Click to send Email'><i>Not available</i></abbr></a></p> <BR> <p class='p-phone-logo'><b>Phone :</b><span class='p-phone-link'><abbr title='select and copy'>+91 81262 90604</abbr></span></p>  <BR>   <p class='p-linkedin-logo'><b>LinkedIn :</b> <a class='p-linkedin-link' href='https://www.linkedin.com/feed/' target='_blank'><abbr title='Go to LinkedIn'><i>Not Available</i><abbr></a></p>",
         //  /mentorfalak details dataset
         "/mentorfalak":"<b>Falak Anis<br><br>Data Science Educator | Theoretical Studies Expert</b><br><br>With 3+ years of experience in education, Falak is a passionate and highly knowledgeable instructor at SDGI University. Specializing in data science and advanced theoretical concepts, she brings a unique blend of expertise in subject matter and human behavior. Her skill in simplifying complex topics makes her a go-to mentor for aspiring data scientists.<br><br>    <p class='p-001'>Enter <code>/infofalak</code> for contact details to connect with your mentor.</p>",
         //  /inforfalak contact details
         "/infofalak":"<b>Contact information [Falak Anis]:</b> <BR><BR> <p class='p-whatsapp-logo'><b>Whatsapp : </b><a class='p-whatsapp-link' href='https://web.whatsapp.com/' target='_blank'><abbr title='web.whatsapp'>+91 94108 80770</abbr></a></p> <BR> <p class='p-email-logo'><b>Email :</b> <a class='p-gmail-link' href='https://mail.google.com/mail/u/0/#inbox?compose=GTvVlcRzBzDLVxJqrslFMcgMrjVhtZmQwbvFCqXSwKHkDrbskmpdNKwSmPrRqVFsdwmcBgKbKWKDz' target='_blank'><abbr title='Click to send Email'>Falakanis26@gmail.com</abbr></a></p> <BR> <p class='p-phone-logo'><b>Phone :</b><span class='p-phone-link'><abbr title='select and copy'>+91 94108 80770</abbr></span></p>  <BR>   <p class='p-linkedin-logo'><b>LinkedIn :</b> <a class='p-linkedin-link' href='https://www.linkedin.com/feed/' target='_blank'><abbr title='Go to LinkedIn'><i>Not Available</i><abbr></a></p>",
         //  /mentordiwakaryadav details dataset
        "/mentordiwakaryadav":"<b>Diwakar Yadav<br><br>Political Science & Data Science Enthusiast | Social Advisor</b><br><br>Diwakar Yadav, a senior student at SDGI University, brings strong expertise in political science, civics, and social environment studies. Along with his academic knowledge, he is proficient in data science, making him a valuable resource for solving data-related challenges.<br> His deep understanding of societal dynamics enables him to offer insightful advice as a social advisor.<br><br>    <p class='p-001'>Enter <code>/infodiwakaryadav</code> for contact details to connect with your mentor.</p>",
        //  /infodiwakaryadav contact details
        "/infodiwakaryadav":"<b>Contact information [Diwakar Yadav]:</b> <BR><BR> <p class='p-whatsapp-logo'><b>Whatsapp : </b><a class='p-whatsapp-link' href='https://chat.whatsapp.com/HM99WTmqYUgFFGNh1ncP42' target='_blank'><abbr title='web.whatsapp'>+91 79823 26470</abbr></a></p> <BR> <p class='p-email-logo'><b>Email :</b> <a class='p-gmail-link' href='https://mail.google.com/mail/u/0/#inbox?compose=CllgCJlFmHwZSHzzwmWxmnrtsdgqsZJhnbSDxPhCTWHWpxFXSwtdsfsPKkjHLRJDbcPPwdWVXXq' target='_blank'><abbr title='Click to send Email'>diwakaryaduvanshi6@gmail.com</abbr></a></p> <BR> <p class='p-phone-logo'><b>Phone :</b><span class='p-phone-link'><abbr title='select and copy'>+91 79823 26470</abbr></span></p>  <BR>   <p class='p-linkedin-logo'><b>LinkedIn :</b> <a class='p-linkedin-link' href='https://www.linkedin.com/in/diwakar-yadav-66033529a/' target='_blank'><abbr title='Go to LinkedIn'>Diwakar Yadav<abbr></a></p>",
        /////////////////////NEXT MENTOR NAME START FROM HERE!!!!!!!!!!!!!!!!!!!
        //Neccessary changes: NAME / Phone No / Email link / Whatsapp link /LinkedIn link / "/commands name" 
        
        
        //|||||||||||||COURSE COMMANDS|||||||||||||||||||||||||||
        
        //DATA SCIENCE
        //"/datascience": "<b>Data Science</b> is an exciting field that combines programming, mathematics, and domain expertise to extract valuable insights from data. It's used in industries like finance, healthcare, and even space exploration!<br><br><p class=p-001>Here's a quick introduction to Data Science:</p> <br><p class=p-477>What is Data Science?</p><br><p><i>Data Science</i> is a blend of tools, algorithms, and machine learning principles used to discover hidden patterns from raw data. It involves the collection, processing, and analysis of data to help organizations make informed decisions.</P><BR><BR><P class=p-477>Looking for the best mentors in Data Science? Check them out on these platforms:</p><BR><a href='https://www.linkedin.com/in/krishnagade/' target='_blank' >Krishna Gade on LinkedIn</a> - Co-founder of Fiddler AI, an expert in AI and data interpretation.<BR><a href='https://www.linkedin.com/in/iambalajis/?originalSubdomain=in' target='_blank' >Sundar Rajan Balaji on LinkedIn</a> - Analytics head at Wipro, specializing in big data and AI.<BR><a href='https://www.linkedin.com/in/anandsubram/' target='_blank'>Anand S on LinkedIn</a> - Founder of Gramener, focused on visual analytics and storytelling with data.<BR><a href='https://www.linkedin.com/in/radhika-kulkarni-01a23232/' target='_blank'>Dr. Radhika Kulkarni on LinkedIn</a> - Analytics expert in optimization and AI.<BR><BR><P class='p-477'>Want to dive into Data Science? Here are some top courses to start learning:</P><BR><a href='https://www.coursera.org/specializations/jhu-data-science' target='_blank'>Data Science Specialization by Johns Hopkins </a>- Coursera<BR><a href='https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/' target='_blank'>Python for Data Science and Machine Learning Bootcamp </a>- Udemy<BR><a href='https://pll.harvard.edu/course/introduction-data-science-python' >Introduction to Data Science with Python</a> - Harvard University<BR><a href='https://nptel.ac.in/courses/106106179' target='_blank' >Data Science for Engineers</a> - NPTEL<BR><BR>",
        "/datascience":"<p class='p-477'> Click the link below to dive into valuable resources Or connect to mentor.</p> <BR> <a  class='explore-link-formatting' href='Data-Science.html' >Explore Data Science</a>",
        
        
        //CloudComputing
        "/cloudcomputing":"<b>Cloud Computing</b> is a revolutionary technology that allows you to access computing resources over the internet, rather than on local servers or personal devices. From data storage to software deployment, it's transforming industries worldwide.<br><br><p class=p-001>Here's a quick introduction to Cloud Computing:</P><BR><p class='p-477'>What is Cloud Computing?</p><BR>Cloud Computing refers to the delivery of various services—like servers, storage, databases, networking, software, and analytics—over the internet (the 'cloud'). Instead of owning physical data centers or servers, companies can rent access to anything from applications to storage from a cloud service provider.<BR><BR><p class='p-477'>Top Cloud Computing Experts in India on Social Platforms:</p><BR><a href='https://www.linkedin.com/in/rohitbhardwaj1/' target='_blank'>Rohit Bhardwaj on LinkedIn</a> - Cloud Leader at Amazon Web Services (AWS) with vast experience in cloud architecture.<BR><a href='https://www.linkedin.com/in/sandeepalur/' target='_blank'>Sandeep Alur on LinkedIn</a> - Director of Microsoft India, cloud enthusiast, and advocate for Microsoft Azure.<BR><a href='https://www.linkedin.com/in/shubhra-mudgal/' target='_blank'>Shubhra Kumar on LinkedIn</a> - Ex-IBM Cloud Consultant with deep expertise in multi-cloud environments.<BR><a href='https://x.com/mcchawla2' target='_blank'>Manish Chawla on Twitter</a>- CIO and Cloud expert specializing in hybrid cloud solutions.<BR><BR>    <p class='p-477'>Check out these top courses:</P><BR><a href='https://www.udemy.com/course/aws-certified-cloud-practitioner-new/?couponCode=IND21PM' target='_blank'>Ultimate AWS Certified Cloud Practitioner CLF-C02</a>- Udemy<BR><a href='https://www.coursera.org/learn/gcp-fundamentals' target='_blank'>Google Cloud Fundamentals: Core Infrastructure</a> -Coursera<BR><a href='https://learn.microsoft.com/en-us/credentials/certifications/azure-fundamentals/?practice-assessment-type=certification' target='_blank'>Microsoft Azure Fundamentals</a>- LearnMicrosoft<BR><a href='https://www.pluralsight.com/browse/cloud-computing' target='_blank'>Cloud Computing  </a>- Pluralsight<BR><BR>",//ArificialIntelligence
        "/ai":"<b>Artificial Intelligence (AI)</b> is transforming industries and shaping the future. From smart assistants like Siri and Alexa to self-driving cars, AI is everywhere!<BR><BR><p class='p-001'>Here’s a quick introduction to Artificial Intelligence:</p><BR><p class='p-477'>What is Artificial Intelligence?</p><BR><i>Artificial Intelligence (AI)</i> is the field of computer science that focuses on creating machines capable of performing tasks that normally require human intelligence. These tasks include visual perception, speech recognition, decision-making, and language translation.<BR><BR><p class='p-477'>Looking for mentors in AI? Here are some great people to follow on social platforms:</p><BR><a href='https://www.linkedin.com/in/andrewng/' target='_blank'>Andrew Ng on LinkedIn</a> - Co-founder of Coursera and a leading AI mentor, especially for machine learning beginners.<BR><a href='https://www.linkedin.com/in/sundarpichai/' target='_blank'>Sundar Pichai on LinkedIn</a> - CEO of Google, passionate about AI advancements and ethics.<BR><a href='https://x.com/rctatman' target='_blank'>Rachael Tatman on Twitter</a> - A machine learning researcher, active in mentoring people learning AI and NLP.<BR><a href='https://www.kaggle.com/' target='_blank'>Deeplearning.ai Mentors (Kaggle)</a> - A dedicated community of mentors helping with AI and deep learning projects.<BR><BR><p class='p-477'>Interested in learning Artificial Intelligence? Start with these top courses:</p><BR><a href='https://www.coursera.org/learn/ai-for-everyone' target='_blank'>AI For Everyone by Andrew Ng</a> - Coursera<BR><a href='https://www.udemy.com/course/artificial-intelligence-az/?couponCode=IND21PM' target='_blank'>Artificial Intelligence A-Z: Learn How to Build an AI</a> (Udemy)<BR><a href='https://www.coursera.org/specializations/deep-learning' target='_blank'>Deep Learning Specialization</a> - Coursera<BR><a href='https://developers.google.com/machine-learning/crash-course/prereqs-and-prework' target='_blank'>Machine Learning Crash Course</a> Google<BR><BR>", // Cybersecurity
        "/cybersecurity":"<b>Cybersecurity</b> is crucial in today's digital world where threats to data and privacy are constant. It involves protecting systems, networks, and data from cyberattacks and ensuring the safety of online information.<BR><BR><p class='p-001'>Here's a quick introduction to Cybersecurity:</p><BR><p class='p-477'>What is Cybersecurity?</p><BR>Cybersecurity refers to the practice of defending computers, servers, mobile devices, networks, and data from malicious attacks. It involves a combination of technologies, processes, and practices designed to safeguard sensitive information from unauthorized access or damage.<BR><BR><p class='p-477'>Looking for top cybersecurity mentors on social platforms? Check these experts out:</p><BR><a href='https://www.linkedin.com/in/saketmodi/' target='_blank'>Saket Modi on LinkedIn </a>- Co-founder & CEO of Lucideus, a leading cybersecurity company.<BR><a href='https://www.linkedin.com/in/kunal-dhingra-7184b415/' target='_blank'>Kunal Dhingra on LinkedIn </a> - Cybersecurity Lead at Microsoft, specializes in cloud security and enterprise solutions.<BR><a href='https://www.linkedin.com/in/anshumanbhartiya/' target='_blank'> Anshuman Bhartiya on LinkedIn </a> - A well-known ethical hacker and founder of SecureLayer7.<BR><a href='https://www.linkedin.com/in/iamrahultyagi/?originalSubdomain=in' target='_blank'>Rahul Tyagi on LinkedIn</a> - Co-founder of Lucideus and a recognized cybersecurity speaker.<BR><BR><p class='p-477'>Check out these courses:</p><BR><a href='https://www.coursera.org/learn/cybersecurity-for-everyone' target='_blank'>Cybersecurity for Everyone</a> - Coursera<BR><a href='https://www.coursera.org/professional-certificates/ibm-cybersecurity-analyst' target='_blank'>IBM Cybersecurity Analyst Professional Certificate</a> - Coursera<BR><a href='https://www.udemy.com/course/penetration-testing/?couponCode=OF83024F' target='_blank'>The Complete Ethical Hacking Course: Beginner to Advanced!</a> - Udemy<BR><a href='https://www.coursera.org/specializations/pythonforcybersecurity' target='_blank'>Python for Cybersecurity Specialization</a> - Coursera <BR><BR>",









};

    // Default response if not found in the predefined responses OR Dataset
    return responses[userMessage.toLowerCase()] || "I am still in the early stages of development — a beta version — so I might make mistakes. I'm constantly improving, learning from interactions to get better every day.<br> If something doesn't seem right or I provide incorrect information, feel free to let me know. Your feedback is valuable in helping me become smarter and more efficient!<br><br><p class=p-001>But I am here to help you, try using <code>/help</code>.</p>";
}

// Sending a message function
function sendMessage() {
    const userInput = document.getElementById("userInput"); //It is finding and selecting the element and assigning it to userInput
    const chatBody = document.getElementById("chat-body");
    const userMessage = userInput.value.trim(); //is used to get or set the current value of userInput (field) mainly its is used in <textarea>/<input>/<select>. Added .trim() to remove extra spaces

    if (userMessage === "") {
        return; // If the input is empty, do nothing
    }

    // Display user's message
    const userMessageDiv = document.createElement("div");  //It creates an element<div> in memory and stores it in variable userMessageDiv, but you can still modify the content/style/attributes.
    userMessageDiv.classList.add("message", "user-message");  //doesn't create new class; it adds existing CSS class to the element userMessageDiv. Classes are predefined in CSS already.
    userMessageDiv.innerHTML = userMessage;  //Assigns userMessage to userMessageDiv. .textContent sets or returns the text content of an HTML element. It is used to get or change the text inside an element.
    chatBody.appendChild(userMessageDiv);  //Adds the user's message (stored in userMessageDiv) to the chat body.

    // Bot response
    const botResponse = getBotResponse(userMessage);  //The result of the function getBotResponse(userMessage) is stored in botResponse
    const botMessageDiv = document.createElement("div"); //Element is created but not added to the webpage yet.
    botMessageDiv.classList.add("message", "bot-message"); //uses existing CSS classes.
    botMessageDiv.innerHTML = botResponse; //botResponse text content is assigned to botMessageDiv
    chatBody.appendChild(botMessageDiv); //adds bot message to the chat body.

    // Clear input field
    userInput.value = ""; //Clears the field after hitting Enter.

    // Scroll to the bottom of the chat
    chatBody.scrollTop = chatBody.scrollHeight; //Moves the scroll position to the very bottom of the chat body.
}

// Listen for Enter key press
document.getElementById("userInput").addEventListener("keypress", function(event) {
    if (event.key === "Enter") {
        sendMessage(); // Call sendMessage when Enter is pressed 
    }
});
